import type { RecoveryReportPayload } from './recoveryReport'

export const DEMO_RECOVERY_REPORT_PAYLOAD: RecoveryReportPayload = {
  schemaVersion: '1.0.0',
  disclaimer:
    'CRI does not diagnose concussion, predict recovery, determine prognosis, or clear return to sport, school, or work. This report organizes patient-reported and authorized clinical records for discussion with a qualified professional.',
  methodologyVersions: {
    symptom: '1.0.0',
    pattern: '1.0.0',
    safety: '1.0.0',
    provenanceSchema: '1.0.0',
  },
  metadata: {
    generatedAt: Date.parse('2026-09-02T12:00:00.000Z'),
    dataCutoffAt: Date.parse('2026-09-02T12:00:00.000Z'),
    requestedByUserId: 'demo-user',
    requestedByRole: 'patient',
    requestedByName: 'Maya Chen',
    rangeStart: '2026-08-19',
    rangeEnd: '2026-09-02',
    rangeKey: '14',
    timeZone: 'UTC',
    dataSource: 'simulated',
    patientDisplayId: 'P-1042',
    patientPreferredName: 'Maya Chen',
    episodeDayLabel: 'Day 15',
  },
  sectionsIncluded: [
    'Recovery episode',
    'Daily symptom check-ins',
    'Symptom trend summary',
    'Sleep & activity context',
    'Recovery timeline events',
    'Observed associations',
    'Questions for your care team',
  ],
  sectionsOmitted: [],
  episode: {
    sourceKind: 'patient_report',
    incidentDate: '2026-08-19',
    injuryContext: 'Soccer collision during practice',
    status: 'active',
    riskLevel: 'Review',
    periodStart: '2026-08-19',
    periodEnd: '2026-09-02',
  },
  symptoms: {
    sourceKind: 'patient_report',
    methodologyVersion: '1.0.0',
    metricName: 'Patient-Reported Symptom Total',
    metricRange: '0–48',
    notRecoveryScore:
      'This is a descriptive sum of self-reported symptoms. It is not a diagnosis, prognosis, or return-to-activity clearance.',
    checkInCount: 12,
    expectedDays: 14,
    gapDays: 2,
    missingDataNote: '2 day(s) without a complete check-in are shown as gaps, not zero values.',
    latestSymptomTotal: 15,
    dimensionSummaries: [
      { dimensionId: 'headache', label: 'Headache', latestRating: 2, averageRating: 2.8, sourceKind: 'patient_report' },
      { dimensionId: 'dizziness', label: 'Dizziness', latestRating: 1, averageRating: 1.9, sourceKind: 'patient_report' },
      { dimensionId: 'fatigue', label: 'Fatigue', latestRating: 2, averageRating: 2.5, sourceKind: 'patient_report' },
      { dimensionId: 'concentration', label: 'Concentration difficulty', latestRating: 2, averageRating: 2.2, sourceKind: 'patient_report' },
    ],
    checkIns: [],
  },
  trends: {
    sourceKind: 'computed_trend',
    direction: 'decreasing',
    readiness: 'sufficient',
    summaryText: 'Patient-reported symptom total decreased over the selected period.',
    disclaimerText:
      'Observed changes reflect patient-reported entries over time and do not establish medical causation, predict recovery, or clear return to activity.',
    dateRangeStart: '2026-08-19',
    dateRangeEnd: '2026-09-02',
  },
  exposure: {
    sourceKind: 'patient_report',
    loggedDays: 12,
    averageSleepHours: 6.8,
    averageScreenMinutes: 95,
    averagePhysicalExertion: 3.2,
  },
  events: {
    sourceKind: 'computed_trend',
    summary: {
      headline: 'Symptoms trending down with gradual activity reintroduction',
      description: '12 of 14 days include symptom check-ins; exposure logs cover most active days.',
      loggedSymptomDays: 12,
      loggedExposureDays: 12,
      gapDays: 2,
    },
    markers: [
      {
        id: 'demo-incident',
        date: '2026-08-19',
        kind: 'incident',
        title: 'Injury / incident reported',
        detail: 'Soccer collision during practice',
      },
    ],
  },
  planAdherence: null,
  patterns: {
    sourceKind: 'computed_trend',
    algorithmVersion: '1.0.0',
    disclaimer:
      'These observations describe temporal associations in patient-reported data. They do not prove causation or guide treatment.',
    patterns: [],
    insufficientNote: 'Not enough paired observations to surface stable associations in this period.',
  },
  safety: {
    sourceKind: 'safety_outcome',
    ruleEngineVersion: '1.0.0',
    eventCount: 0,
    evaluations: [],
    missingDataNote: 'No safety escalations recorded in this period.',
  },
  encounters: null,
  discussionQuestions: [
    'I missed 2 check-in day(s) in this period. Could inconsistent logging affect how we interpret my symptoms?',
    'Based on this summary, what should I monitor next — and when should I contact you before my next visit?',
  ],
}
